/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MakeQuiz;

import java.awt.GridLayout;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author derek
 */
public class NewTest extends javax.swing.JFrame {
     /**
     * Creates new form NewTest
     */
    JPanel innerMultiPanel;
    String lastSelection;
    int numQuestions;
    int curQuestion;
    
    public NewTest() {
        initComponents();
        setVisible(true);
        lastSelection = "Multiple Choice";
        multiPanel.setLayout(new GridLayout(1,1));
        innerMultiPanel = new NewTestMC();
        innerMultiPanel.setVisible(true);
        multiPanel.add(innerMultiPanel);
        numQuestions=1;
        curQuestion=1;
        updateLabel();
    }

    void updateLabel()
    {
        jLabel2.setText("Question " + curQuestion + "/" + numQuestions);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sectionType = new javax.swing.JComboBox();
        buttonFinish = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonCancel1 = new javax.swing.JButton();
        buttonFinish1 = new javax.swing.JButton();
        multiPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        buttonFinish2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Test");
        setAlwaysOnTop(true);

        jLabel5.setText("Question Type:");

        sectionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Multiple Choice", "True or False", "Essay" }));
        sectionType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionTypeActionPerformed(evt);
            }
        });

        buttonFinish.setText("Save");
        buttonFinish.setPreferredSize(new java.awt.Dimension(143, 25));
        buttonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishActionPerformed(evt);
            }
        });

        buttonCancel.setText("Exit Without Saving");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonCancel1.setText("< Previous Question");
        buttonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancel1ActionPerformed(evt);
            }
        });

        buttonFinish1.setText("Next Question >");
        buttonFinish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinish1ActionPerformed(evt);
            }
        });

        multiPanel.setBorder(new javax.swing.border.MatteBorder(null));
        multiPanel.setMinimumSize(new java.awt.Dimension(656, 250));
        multiPanel.setName("");
        multiPanel.setPreferredSize(new java.awt.Dimension(656, 250));

        javax.swing.GroupLayout multiPanelLayout = new javax.swing.GroupLayout(multiPanel);
        multiPanel.setLayout(multiPanelLayout);
        multiPanelLayout.setHorizontalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        multiPanelLayout.setVerticalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jButton1.setText("New Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonFinish2.setText("Delete Question");
        buttonFinish2.setMaximumSize(new java.awt.Dimension(143, 25));
        buttonFinish2.setMinimumSize(new java.awt.Dimension(143, 25));
        buttonFinish2.setPreferredSize(new java.awt.Dimension(143, 25));
        buttonFinish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinish2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sectionType, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonFinish2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonFinish1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonFinish, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(multiPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(sectionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addComponent(multiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonFinish2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonFinish1)
                        .addComponent(buttonCancel1))
                    .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishActionPerformed
        JFrame frame = new JFrame();
        int i = JOptionPane.showConfirmDialog(frame,"Save and exit?","Save New Quiz",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_buttonFinishActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        JFrame frame = new JFrame();
        int i = JOptionPane.showConfirmDialog(frame,"Exit without saving?","Exit Quiz Creation",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancel1ActionPerformed
       curQuestion--;
       if(curQuestion < 1) curQuestion=numQuestions;
       updateLabel();
    }//GEN-LAST:event_buttonCancel1ActionPerformed

    private void buttonFinish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinish1ActionPerformed
        curQuestion++;
        if(curQuestion > numQuestions) curQuestion=1;
        updateLabel();
    }//GEN-LAST:event_buttonFinish1ActionPerformed

    private void buttonFinish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinish2ActionPerformed
        newQuestion();
        numQuestions--;
        if(numQuestions==0) numQuestions = 1;
        if(curQuestion > numQuestions) curQuestion = numQuestions;
        updateLabel();
    }//GEN-LAST:event_buttonFinish2ActionPerformed

    private void sectionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionTypeActionPerformed
        JComboBox cbPick = (JComboBox) evt.getSource();
        lastSelection = cbPick.getSelectedItem().toString();
        newQuestion();
        updateLabel();
    }//GEN-LAST:event_sectionTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newQuestion();
        numQuestions++;
        curQuestion = numQuestions;
        updateLabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    void newQuestion()
    {
        multiPanel.removeAll();
        multiPanel.setLayout(new GridLayout(1, 1));

        if (lastSelection.equals("Multiple Choice")) {
            innerMultiPanel = new NewTestMC();
        } else if (lastSelection.equals("True or False")) {
            innerMultiPanel = new NewTestTF();
        } else if (lastSelection.equals("Essay")) {
            innerMultiPanel = new NewTestEs();
        }
        innerMultiPanel.setVisible(true);
        multiPanel.add(innerMultiPanel);
        multiPanel.repaint();
        multiPanel.validate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCancel1;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonFinish1;
    private javax.swing.JButton buttonFinish2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel multiPanel;
    private javax.swing.JComboBox sectionType;
    // End of variables declaration//GEN-END:variables
}
