/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MakeQuiz;

/**
 *
 * @author derek
 */
public class NewTestEs extends javax.swing.JPanel {

    /**
     * Creates new form NewTestEs
     */
    public NewTestEs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EssayTextBox = new javax.swing.JTextField();

        setBorder(new javax.swing.border.MatteBorder(null));
        setMinimumSize(new java.awt.Dimension(656, 250));
        setPreferredSize(new java.awt.Dimension(656, 250));

        EssayTextBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EssayTextBox.setText("Please enter your question here.");
        EssayTextBox.setMinimumSize(new java.awt.Dimension(656, 250));
        EssayTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EssayTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EssayTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EssayTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EssayTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EssayTextBoxActionPerformed
        // TODO add your handling code here:
        EssayTextBox.setText("");
        EssayTextBox.setMinimumSize(new java.awt.Dimension(656, 250));
    }//GEN-LAST:event_EssayTextBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EssayTextBox;
    // End of variables declaration//GEN-END:variables
}
