/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TakeQuizPackage;

import java.awt.GridLayout;
import proctolearningsystem.QuizQuestion;

/**
 *
 * @author lbissonnette
 */
public class MCAnswerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MCAnswerPanel
     */
    int numAnswers;
    public MCAnswerPanel() {
        initComponents();
        setLayout(new GridLayout(5,1));
        numAnswers=0;
    }
    
    public void addQuestion(QuizQuestion question)
    {
        
        
    }

    public void addAnswer(String Answer)
    {
        numAnswers++;
        add(new AnswerQSlot(numAnswers,buttonGroup1,Answer));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
